### grp

# Course: _Introduction to Python_

## _1. Python Basics_:
-  calculator
-  variables
-  basic types:
    -  int [whole numbers]
    -  float [decimal numbers]
    -  str [text]
    -  bool [true / false]
-  type conversion

#### addition and subtraction

In [1]:
print(5 + 5)
print(5 - 5)

10
0


#### multiplication and division

In [2]:
print(3 * 5)
print(10 / 2)

15
5.0


#### exponential power

In [3]:
print(4 ** 2)

16


#### modulo (remainder)

In [4]:
print(18 % 7)

4


#### concat strings

In [5]:
desc = "compound interest"
doubledesc = desc + desc
print(doubledesc)

compound interestcompound interest


#### variables

In [6]:
savings = 100
print(savings)

100


#### variable calculations

In [7]:
savings = 100 # int
factor = 1.10 # float
result = savings * factor ** 7
print(result)

194.87171000000012


#### other variable types

In [8]:
desc = "compound interest" # str
profitable = True # bool

#### find variable type

In [9]:
print(type(savings))
print(type(factor))
print(type(desc))
print(type(profitable))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


#### type conversion

In [10]:
pi_string = "3.1415926" # string
pi_float = float(pi_string) # convert string to float
print(type(pi_float))
print(pi_float)

<class 'float'>
3.1415926


#### printout (combine types)

In [11]:
savings = 100
result = 100 * 1.10 ** 7
print("I started with $" + str(savings) + " and now have $" + str(result) + ". Awesome!")

I started with $100 and now have $194.87171000000012. Awesome!


## _2. Python Lists_:
-  lists [collection of elements]
-  sublists [lists within list]
-  subsetting lists:
    -  select index
    -  slicing [start (inclusive) : end (exclusive)]
-  list manipulation:
    -  replace elements
    -  add elements
    -  delete elements
    -  copy list

### _index locations change after manipulation!_

#### list

In [12]:
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

areas = [hall, kit, liv, bed, bath]

print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


#### mixed type list

In [13]:
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

areas = ["hallway", hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]

print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


#### list of lists (sublist)

In [14]:
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]

print(house)
print(type(house))

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


#### subset list

In [15]:
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

print(areas[1]) # 2nd element
print(areas[-1]) # last element
print(areas[5]) # 6th element

11.25
9.5
20.0


#### slice list

In [16]:
x = ["a", "b", "c", "d"]

print(x[:2])
print(x[2:])
print(x[:])

['a', 'b']
['c', 'd']
['a', 'b', 'c', 'd']


In [17]:
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

downstairs = areas[:6]
upstairs = areas[-4:]

print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


#### subset list of lists + slicing

In [18]:
x = [["a", "b", "c"],
     ["d", "e", "f"],
     ["g", "h", "i"]]

print(x[2][0]) # 3rd sublist / 1st element
print(x[2][:2]) # 3rd sublist / 1st and 2nd element

g
['g', 'h']


#### replace list elements

In [19]:
x = ["a", "b", "c", "d"]
x[1] = "r"
x[2:] = ["s", "t"]

print(x)

['a', 'r', 's', 't']


In [20]:
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

areas[-1] = 10.50
areas[4] = "chill zone"

print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]


#### add list elements

In [21]:
x = ["a", "b", "c", "d"]
y = x + ["e", "f"]

print(x)
print(y)

['a', 'b', 'c', 'd']
['a', 'b', 'c', 'd', 'e', 'f']


In [22]:
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

areas_1 = areas + ["poolhouse", 24.5]
areas_2 = areas_1 + ["garage", 15.45]

print(areas)
print(areas_1)
print(areas_2)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]


#### delete list elements

In [23]:
x = ["a", "b", "c", "d"]
del(x[1])

print(x)

['a', 'c', 'd']


In [24]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

del(areas[-4:-2]) # remove poolhouse and value elements

print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'garage', 15.45]


#### copy list

In [25]:
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

areas_copy = areas[:] # or areas_copy = list(areas)
areas_copy[0] = 5.0

print(areas)
print(areas_copy)

[11.25, 18.0, 20.0, 10.75, 9.5]
[5.0, 18.0, 20.0, 10.75, 9.5]


## _3. Functions [reusable code] and Packages_:
-  standard build-in functions:
    -  max
    -  min
    -  round
    -  help
    -  print
    -  type
    -  int
    -  str
    -  bool
    -  float
    -  len
    -  sorted
-  function arguments
-  methods [functions that belong to objects (i.e. "***everything***")]

-  packages [directory of py scripts]:
    -  each script = ***module***
    -  specify functions, methods, types

#### help function

In [26]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



#### multiple arguments

In [27]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [28]:
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

full = first + second
full_sorted = sorted(full, reverse=True) # descending order

print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


#### string methods

In [29]:
place = "poolhouse"

place_up = place.upper()

print(place)
print(place_up)
print(place.count('o'))

poolhouse
POOLHOUSE
3


#### list methods

In [30]:
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

print(areas.index(20.0))
print(areas.count(9.50))

2
1


In [31]:
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

areas.append(24.5); areas.append(15.45)

print(areas)
areas.reverse()
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


#### import package

In [32]:
import math

r = 0.43
C = 2 * math.pi * r
A = math.pi * r**2

print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


#### selective import

In [33]:
from math import radians

r = 192500
dist = r * radians(12)

print(dist)

40317.10572106901


## _4. NumPy [numeric python]_:
-  calculations over entire arrays (***python lists do not support calculations element wise***)
-  numpy arrays (***contain only one type*** [int, float, string, boolean])
-  numpy subsetting
-  2D numpy arrays (ndarray = ***N-dimensional array***):
    -  each sublist within lists corresponds to a row
    -  numpy.shape => (row, column)
    -  subsetting => array[row,column] or array[row][column]
-  statistics:
    -  mean
    -  median
    -  correlation coefficient
    -  standard deviation

#### import numpy w/ alias

In [34]:
import numpy as np

#### numpy array

In [35]:
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

np_baseball = np.array(baseball)

print(type(np_baseball))

<class 'numpy.ndarray'>


#### numpy array calculation

In [36]:
height_inches = [77,75,72,72,72,71,70,70,69,67]

np_height_in = np.array(height_inches)
print(np_height_in)

np_height_meters = np_height_in * 0.0254 # convert height from inches to meters
print(np_height_meters)

[77 75 72 72 72 71 70 70 69 67]
[1.9558 1.905  1.8288 1.8288 1.8288 1.8034 1.778  1.778  1.7526 1.7018]


In [37]:
weight_lbs = [211,205,188,192,175,166,172,162,165,161]

np_height_meters = np.array(height_inches) * 0.0254
np_weight_kg = np.array(weight_lbs) * 0.453592 # convert weight from lbs to kg

bmi = np_weight_kg / np_height_meters ** 2 # bmi

print(bmi)

[25.02067133 25.62295933 25.4971013  26.03959282 23.73400387 23.15204424
 24.67915695 23.24432224 24.3659706  25.2158855 ]


#### numpy array subset

In [38]:
x = [4 , 9 , 6, 3, 1]
y = np.array(x)

print(y[1])

9


In [39]:
high = y > 5
y[high]

array([9, 6])

In [40]:
np_height_meters = np.array(height_inches) * 0.0254
np_weight_kg = np.array(weight_lbs) * 0.453592

bmi = np_weight_kg / np_height_meters ** 2
light = bmi < 24

print(light)
print(bmi[light])

[False False False False  True  True False  True False False]
[23.73400387 23.15204424 23.24432224]


#### numpy arrays cannot contain elements w/ different types (True = 1; False = 0)

In [41]:
print(np.array([True, 1, 2]) + np.array([3, 4, False]))
print(np.array([4, 3, 0]) + np.array([0, 2, 2]))

[4 5 2]
[4 5 2]


#### numpy array subsets

In [42]:
np_weight = np.array(weight_lbs)
np_height = np.array(height_inches)

print(weight_lbs)
print(height_inches)
print(np_weight[7]) # weight at index 7
print(np_height[3:8]) # sub-array from index 3 up to and including index 7

[211, 205, 188, 192, 175, 166, 172, 162, 165, 161]
[77, 75, 72, 72, 72, 71, 70, 70, 69, 67]
162
[72 72 71 70 70]


#### 2d numpy array

In [43]:
baseball = [[180, 78.4], # 4 rows; 2 columns
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

np_baseball = np.array(baseball)

print(type(np_baseball))
print(np_baseball.shape) # 4 rows; 2 columns

<class 'numpy.ndarray'>
(4, 2)


#### 2d numpy array subsetting

In [44]:
x = [["a", "b"], ["c", "d"]] # regular list of lists

for i in x: print(i)
print("="*10)    

print([x[0][0], x[1][0]])

np_x = np.array(x) # 2d numpy array

print(np_x[:,0]) # every row; 1st column

['a', 'b']
['c', 'd']
['a', 'c']
['a' 'c']


In [45]:
np_baseball = np.array(baseball)
print(np_baseball)
print("="*10)    

print(np_baseball[2,:]) # 3rd row (2nd element); every column
print("="*10)    

np_weight = (np_baseball[:,0]) # every row; 1st column (0th element)
for i in np_weight: print(i)
print("="*10)    

print(np_baseball[3,0]) # 4 row (3rd element); 1st column (0th element)

[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]
[210.   98.5]
180.0
215.0
210.0
188.0
188.0


#### 2d element-wise arithmetic

In [46]:
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

print(np_mat * 2) # multiply element-wise matrix by 2
print("="*10)    

print(np_mat + np.array([10, 10])) # add vector to matrix element-wise
print("="*10)    

print(np_mat + np_mat) # add matrix to matrix element-wise

[[ 2  4]
 [ 6  8]
 [10 12]]
[[11 12]
 [13 14]
 [15 16]]
[[ 2  4]
 [ 6  8]
 [10 12]]


In [47]:
baseball_matrix = [[180, 78.4, 22.99], # 4 rows; 3 columns
            [215, 102.7, 34.69],
            [210, 98.5, 30.78],
            [188, 75.2, 25.19]]

updated_matrix = [[1.2303559, -11.16224898, 1], # 4 rows; 3 columns
       [1.02614252, 16.09732309, 1],
       [1.1544228, 5.08167641, 1],
       [1.09349925,   4.23890778, 1]]

np_baseball = np.array(baseball_matrix)
print(np_baseball + updated_matrix) # element-wise matrix addition

conversion = np.array([0.0254, 0.453592, 1])
print(np_baseball * conversion) # element-wise matrix multiplication

[[181.2303559   67.23775102  23.99      ]
 [216.02614252 118.79732309  35.69      ]
 [211.1544228  103.58167641  31.78      ]
 [189.09349925  79.43890778  26.19      ]]
[[ 4.572     35.5616128 22.99     ]
 [ 5.461     46.5838984 34.69     ]
 [ 5.334     44.678812  30.78     ]
 [ 4.7752    34.1101184 25.19     ]]


### numpy statistics

In [48]:
np_height = (np_baseball[:,0]) # all rows; 1st column (0th element)
print(np_baseball)
print("="*10)
print(np_height)
print(np.mean(np_height))
print(np.median(np_height))

[[180.    78.4   22.99]
 [215.   102.7   34.69]
 [210.    98.5   30.78]
 [188.    75.2   25.19]]
[180. 215. 210. 188.]
198.25
199.0


In [49]:
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

med = np.median(np_baseball[:,0])
print("Median: " + str(med))

stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

corr = np.corrcoef(np_baseball[:,0], np_baseball[:,1]) # correlation between 1st and 2nd column
print("Correlation: " + str(corr))

Average: 198.25
Median: 199.0
Standard Deviation: 14.635146053251399
Correlation: [[1.         0.95865738]
 [0.95865738 1.        ]]


In [50]:
positions = ['GK', 'M', 'A', 'D']
heights = [191, 184, 185, 180]

np_heights = np.array(heights)
np_positions = np.array(positions)

gk_heights = np_heights[np_positions == 'GK'] # goalkeepers height
other_heights = np_heights[np_positions != 'GK'] # other player's height

print("Median height of goalkeepers: " + str(np.median(gk_heights)))
print("Median height of other players: " + str(np.median(other_heights)))

Median height of goalkeepers: 191.0
Median height of other players: 184.0


### grp